export const imageData = [
  {
    prompt: "Cyberpunk version of San Francisco with dramatic neon lighting, cinematic, picturesque, unreal",
    author: "Sam Cheng",
    ai: "MidJourney",
    notes: "Specified --ar 9:16",
    img: "/images/cyberpunkSF.png",
    gridColumn: "span 1",
    gridRow: "span 2",
  },
  {
    prompt: "A Japanese temple made out of clouds surrounded by cherry blossom trees with the ground made out of wooden planks, digital art",
    author: "Sam Cheng",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to add a floating tree on the left and a meadow on the right.",
    img: "/images/cloudTemple.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A Japanese temple made out of clouds surrounded by cherry blossom trees with the ground made out of wooden planks, digital art",
    author: "Sam Cheng",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to add a floating island",
    img: "/images/cloudTempleMobile.png",
    gridColumn: "span 1",
    gridRow: "span 2",
  },
  {
    prompt: "A Cyberpunk Tokyo with samurais with neon lighting, digital art",
    author: "Brandon H",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/neonTokyo.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "Colorful end of the world, digital art",
    author: "Grant Sloan",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/endOfWorld.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A portal into a world of cherry blossom trees, digital art",
    author: "Sam Cheng",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/portalCherryBlossom.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A jungle waterfall, picturesque, landscape, vibrant, colorful",
    author: "Sam Cheng",
    ai: "MidJourney",
    notes: "No Notes",
    img: "/images/jungleWaterfall.png",
    gridColumn: "span 1",
    gridRow: "span 1",
  },
  {
    prompt: "A hawaiian shirt  blowing through an old japanese town in the style of anime, picturesque, vibrant, anime, cinematic",
    author: "Brandon H",
    ai: "MidJourney & DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/japaneseVillage.png",
    gridColumn: "span 3",
    gridRow: "span 1",
  },
  {
    prompt: "a village surrounded in the icy wilderness with snow and lanterns, Digital Art",
    author: "Tobais Sin",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/snowVillage.png",
    gridColumn: "span 3",
    gridRow: "span 1",
  },
  {
    prompt: "San Francisco with dramatic neon lighting, cinematic, picturesque, unreal",
    author: "Sam Cheng",
    ai: "MidJourney",
    notes: "No Notes",
    img: "/images/squareCyberSF.png",
    gridColumn: "span 1",
    gridRow: "span 1",
  },
  {
    prompt: "Cyberpunk massive purple and blue snake with green eyes in an abyss, digital art",
    author: "Grant Sloan",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/cyberpunkSnake.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A colorful alien space ship abducting a person with people running away from it, digital art",
    author: "Will Kizer",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/ufo.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A man surfing in a bowl of tomato soup",
    author: "Maddox Hom",
    ai: "DALL·E 2",
    notes: "No Notes",
    img: "/images/surfingTomato.png",
    gridColumn: "span 2",
    gridRow: "span 2",
  },
  {
    prompt: "vibrant, steampunk, and overgrown version of New York City, digital art",
    author: "Maddox Hom",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/steampunkNYC.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A city full of skyscrapers that is half under water with the camera half under water, digital art, steampunk, vibrant",
    author: "Sam Cheng",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/underwaterCity.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
  {
    prompt: "A vaporwave style car speeding down a lonely Japanese road at night with stars filling the sky, digital art",
    author: "Sam Cheng",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/vaporwaveCar.png",
    gridColumn: "span 1",
    gridRow: "span 2",
  },
  {
    prompt: "An ocean at sunset full of clouds and floating lanterns, digital art",
    author: "Sam Cheng",
    ai: "DALL·E 2",
    notes: "Used Dalle's outpainting to continue the photo",
    img: "/images/oceanLanterns.png",
    gridColumn: "span 2",
    gridRow: "span 1",
  },
]