// Component for metatags

// Use twitter card validator to test: https://cards-dev.twitter.com/validator

import Head from 'next/head';

export default function Metatags({
  title = 'AI Wallpapers',
  description = 'Stunning Wallpapers Created By AI - Generated by Artificial Intelegence and not edited at all, These images are striking and beautiful',
  image = 'https://aiwallpapers.samalander.repl.co/card.png',
}) {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={description}/>
        
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:site" content="www.samalander.dev" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={image} />

      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:image" content={image} />

      <link rel="icon" href="https://aiwallpapers.samalander.repl.co/favicon.ico" type="image/x-icon"/>
    </Head>
  );
}