import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import Images from '../components/ImageFeed'
import Metatags from '../components/Metatags'

import {React, useEffect, useRef} from 'react';

import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const header = useRef();
  const backgroundTxt = useRef();
  const down = useRef();

  useEffect(() => {
    gsap.to(backgroundTxt.current, {
      x: "-18vw",
      scrollTrigger: {
        trigger: backgroundTxt.current,
        scrub: true,
        start: "center center",
        end: "+=1000"
      }
    })
    gsap.to(down.current, {
      y: "30vh",
      scrollTrigger: {
        trigger: down.current,
        scrub: true,
        start: "center center",
        end: "+=1000"
      }
    })
  })
  
  return (<>
    <Metatags/>
    <header id={styles.header} ref={header}>
      <h1>Stunning Wallpapers 
Created By AI</h1>
      <h2 ref={backgroundTxt} className="outline">AI Wallpapers</h2>
      <p>Generated by Artificial Intelligence and not edited at all, these images are striking and beautiful</p>
      <a href="#gallery" ref={down}><img src="/media/down.svg" id={styles.down}/></a>
      <img src="/images/cloudTemple.png" id={styles.backgroundImg}/>
    </header>
    <main id={styles.main}>
      <h2 id="gallery">Wallpaper Gallery</h2>
      <Images/>
    </main>
  </>)
}